In [ ]:
# setup
%pip install -q pandas numpy scikit-learn

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("titanic_dataset.csv")
print("Shape of the dataset:", df.shape)
print("Columns in the dataset:", df.columns.tolist())
df.head()

Shape of the dataset: (891, 15)
Columns in the dataset: ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
# dropping "alive" column as it is redundant due to the presence of "survived" column
df = df.drop(columns=["alive"])

In [5]:
print("Shape of the dataset:", df.shape)
print("Columns in the dataset:", df.columns.tolist())
df.head()

Shape of the dataset: (891, 14)
Columns in the dataset: ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alone']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,True

In [6]:
# Drop rows with missing target if any (safe before train test split)
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alone            0
dtype: int64

In [7]:
target = "survived"

In [8]:
missing_target_count = df[target].isna().sum()
print("Rows with missing target:", missing_target_count)

# drop the rows that has missing target value
df = df.dropna(subset=[target])

print("Shape after dropping missing target rows", df.shape)

Rows with missing target: 0
Shape after dropping missing target rows (891, 14)

In [9]:
# Separate X (features) and y (target)

In [10]:
X = df.drop(columns=[target])
y = df[target]

In [11]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (891, 13)
y shape: (891,)

In [12]:
X.head()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,False
1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,False
2,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,True
3,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,False
4,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,True

In [13]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

In [14]:
print("Target distribution on full data:")
print(y.value_counts())

print("-"*50)

print("Target distribution in percentage")
print(y.value_counts(normalize=True).round(4)*100)

Target distribution on full data:
survived
0    549
1    342
Name: count, dtype: int64
--------------------------------------------------
Target distribution in percentage
survived
0    61.62
1    38.38
Name: proportion, dtype: float64

In [15]:
# X (features)  -> training_features (X_train); test_features (X_test)

# y (target)    -> training_targets (y_train); test_targets (y_test)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y,   # even distribution of target in train and test sets
)

In [17]:
print("Shapes:")
print("X:", X.shape)
print("y:", y.shape)
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

Shapes:
X: (891, 13)
y: (891,)
X_train: (712, 13)
X_test: (179, 13)
y_train: (712,)
y_test: (179,)

In [18]:
X_train[:5]

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
692,3,male,NaN,0,0,56.4958,S,Third,man,True,NaN,Southampton,True
481,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,True
527,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,True
855,3,female,18.0,0,1,9.3500,S,Third,woman,False,NaN,Southampton,False
801,2,female,31.0,1,1,26.2500,S,Second,woman,False,NaN,Southampton,False

In [19]:
y_train[:5]

692    1
481    0
527    0
855    1
801    1
Name: survived, dtype: int64

In [20]:
print(X_train.shape)
print(y_train.shape)

(712, 13)
(712,)

In [21]:
X_test[:5]

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
565,3,male,24.0,2,0,24.1500,S,Third,man,True,NaN,Southampton,False
160,3,male,44.0,0,1,16.1000,S,Third,man,True,NaN,Southampton,False
553,3,male,22.0,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,True
860,3,male,41.0,2,0,14.1083,S,Third,man,True,NaN,Southampton,False
241,3,female,NaN,1,0,15.5000,Q,Third,woman,False,NaN,Queenstown,False

In [22]:
y_test[:5]

565    0
160    0
553    1
860    0
241    1
Name: survived, dtype: int64

In [23]:
print(X_test.shape)
print(y_test.shape)

(179, 13)
(179,)

In [24]:
# Training process:

# X_train, y_train -> ML model learns the pattern -> trained ML model


# Evaluation Process

# X_test -> trained ML model -> y_pred (prediction from the trained model)

# Compare y_pred & y_test (true labels)

In [25]:
print("Target distribution on full data:")
print(y.value_counts())

print("Target distribution in percentage")
print(y.value_counts(normalize=True).round(3))

print("-"*50)

print("Target distribution on training data:")
print(y_train.value_counts())

print("Target distribution in percentage")
print(y_train.value_counts(normalize=True).round(3))

print("-"*50)

print("Target distribution on test data:")
print(y_test.value_counts())

print("Target distribution in percentage")
print(y_test.value_counts(normalize=True).round(3))

print("-"*50)

Target distribution on full data:
survived
0    549
1    342
Name: count, dtype: int64
Target distribution in percentage
survived
0    0.616
1    0.384
Name: proportion, dtype: float64
--------------------------------------------------
Target distribution on training data:
survived
0    439
1    273
Name: count, dtype: int64
Target distribution in percentage
survived
0    0.617
1    0.383
Name: proportion, dtype: float64
--------------------------------------------------
Target distribution on test data:
survived
0    110
1     69
Name: count, dtype: int64
Target distribution in percentage
survived
0    0.615
1    0.385
Name: proportion, dtype: float64
--------------------------------------------------

In [26]:
train_df = X_train.copy()
train_df[target] = y_train.values

test_df = X_test.copy()
test_df[target] = y_test.values

In [27]:
train_df.to_csv("titanic_train_raw.csv", index=False)
test_df.to_csv("titanic_test_raw.csv", index=False)

print("\nSaved:")
print(" - titanic_train_raw.csv")
print(" - titanic_test_raw.csv")

Saved:
 - titanic_train_raw.csv
 - titanic_test_raw.csv